ALTER TABLE interventions
    ADD COLUMN heart_rate VARCHAR(10) NULL,
    ADD COLUMN blood_pressure VARCHAR(10) NULL,
    ADD COLUMN spo2 VARCHAR(10) NULL,
    ADD COLUMN temperature VARCHAR(10) NULL,
    ADD COLUMN consciousness VARCHAR(20) NULL,
    ADD COLUMN oxygen_placed BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN ecg_done BOOLEAN NOT NULL DEFAULT FALSE;